language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/labstack/echo
  - go get github.com/smartystreets/goconvey
  - go get github.com/flosch/pongo2

script:
  - go test -v .
  - $HOME/gopath/bin/goveralls -service=travis-ci
  
